# Generated by Django 5.2.4 on 2025-08-09 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classification',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='inventory.medicine'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='inventory.classification'),
        ),
    ]
