# Generated by Django 5.2.4 on 2025-08-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_classification_approved_classification_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.classification'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dispensed', 'Dispensed'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stock_after',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stock_before',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
