# Generated by Django 5.2.4 on 2025-09-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_auditlog_user_alter_inventory_medicine_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.RemoveField(
            model_name='classification',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='classification',
        ),
        migrations.AddField(
            model_name='medicine',
            name='classification',
            field=models.ManyToManyField(blank=True, related_name='medicines', to='inventory.classification'),
        ),
    ]
