# Generated by Django 5.2.4 on 2025-11-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_inventory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="intended_for",
            field=models.CharField(
                choices=[
                    ("adult", "Adult"),
                    ("children", "Children"),
                    ("both", "Both"),
                ],
                default="both",
                max_length=20,
            ),
        ),
    ]
