# Generated by Django 5.2.4 on 2025-11-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_medicine_intended_for"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="intended_for",
            field=models.CharField(
                choices=[
                    ("adult", "Adult"),
                    ("pediatric", "Pediatric"),
                    ("both", "Both"),
                ],
                default="both",
                max_length=20,
            ),
        ),
    ]
