# Generated by Django 5.2.4 on 2025-11-30 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_transactionbatch_transaction_batch"),
    ]

    operations = [
        migrations.CreateModel(
            name="DosageInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="dosage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="inventory.dosageinstruction",
            ),
        ),
    ]
