# Generated by Django 5.2.7 on 2025-12-02 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_transaction_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredInventory',
            fields=[
            ],
            options={
                'verbose_name': 'Expired stock',
                'verbose_name_plural': 'Expired stocks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventory',),
        ),
    ]
