# Generated by Django 5.2.4 on 2025-12-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.CharField(default="expired notification", max_length=255),
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(default="expired", max_length=50),
        ),
    ]
